INSERT INTO course_offering (course,quarter,instructor) VALUES ('CMPSC 56','F19','Conrad');
INSERT INTO course_offering (course,quarter,instructor) VALUES ('CMPSC 16','F19','Mirza');
INSERT INTO course_offering (course,quarter,instructor) VALUES ('CMPSC 160','F19','Ding');
INSERT INTO course_offering (course,quarter,instructor) VALUES ('CMPSC 130A','W20','Koc');
INSERT INTO course_offering (course,quarter,instructor) VALUES ('CMPSC 130B','w20','Lokshtanov');
INSERT INTO tutor (fname,lname,email) VALUES ('Scott','Chow','scottpchow@example.org');
INSERT INTO tutor (fname,lname,email) VALUES ('Zach','Sisco','zachsisco@example.org');
INSERT INTO tutor (fname,lname,email) VALUES ('Yinon','Rousso','yinonRousso@example.org');
INSERT INTO tutor (fname,lname,email) VALUES ('Kate','Perkins','kateperkins@example.org');
INSERT INTO tutor (fname,lname,email) VALUES ('George','Kripac','Georgekripac@example.org');
INSERT INTO tutor (fname,lname,email) VALUES ('George','Kripac','Georgekripac@example.org');
INSERT INTO tutor_assignment (course_offering_id,tutor_id) VALUES (1,1);
